name: Update

on:
  push:
    branches: [ 'main' ]
  schedule:
    - cron: '0 2 * * *' # every day at 2:00 am

env:
  CARGO_TERM_COLOR: always

jobs:
  generate:
    name: Generate index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Checkout IITC-CE/Community-plugins
        uses: actions/checkout@v4
        with:
          repository: IITC-CE/Community-plugins
          path: Community-plugins
          sparse-checkout: metadata

      - name: Generate index
        run: cargo run -- --repository ./Community-plugins --output-path ./dist/index.json

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

  deploy:
    name: Deploy to GitHub Page
    runs-on: ubuntu-latest
    needs: generate
    permissions:
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy index
        id: deployment
        uses: actions/deploy-pages@v4